'use client'

import { motion } from 'framer-motion'
import { Brain, BookMarked, MessageSquare, Calendar, BarChart3, Download } from 'lucide-react'

const features = [
  {
    icon: Brain,
    title: 'AI Roadmap Generator',
    description: 'Get personalized learning paths generated by AI based on your goals, skill level, and available time.',
  },
  {
    icon: BookMarked,
    title: 'Interactive Chapters',
    description: 'Structured learning modules with lessons, resources, and practice exercises. Track your progress visually.',
  },
  {
    icon: MessageSquare,
    title: 'AI Mentor Assistant',
    description: 'Chat with your personal AI mentor that understands your roadmap and provides contextual guidance.',
  },
  {
    icon: Calendar,
    title: 'Study Planner',
    description: 'Intelligent scheduling that breaks down your roadmap into daily and weekly actionable tasks.',
  },
  {
    icon: BarChart3,
    title: 'Progress Tracking',
    description: 'Visualize your learning journey with progress bars, streaks, and mastery indicators.',
  },
  {
    icon: Download,
    title: 'Save & Export',
    description: 'Export your roadmap as PDF, share with others, or sync progress across devices.',
  },
]

export function Features() {
  return (
    <section id="features" className="py-20 bg-paper-50">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center max-w-2xl mx-auto mb-16"
        >
          <h2 className="text-3xl sm:text-4xl font-serif font-bold text-ink-900 mb-4">
            Everything You Need to Learn Effectively
          </h2>
          <p className="text-ink-500 text-lg">
            A complete toolkit designed to make your learning journey structured,
            engaging, and successful.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 animate-stagger">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.1 }}
            >
              <div className="bg-white rounded-xl border border-paper-300 p-6 hover:shadow-medium transition-all duration-200 h-full">
                <div className="w-12 h-12 bg-accent/10 rounded-lg flex items-center justify-center mb-4">
                  <feature.icon className="w-6 h-6 text-accent" />
                </div>
                <h3 className="text-xl font-serif font-bold text-ink-900 mb-2">
                  {feature.title}
                </h3>
                <p className="text-ink-500 leading-relaxed">
                  {feature.description}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
